const products = [
{   id: 1,
    imageSrc:"images/Cleanser.png",
    altText:"cleanser image",
    productBrand:"Tatcha",
    productName:"Rice Wash",
    purchaseDate:"01/01/2023",
    expiryDate:"01/01/2024",
},

{   id: 2,
    imageSrc:"images/Toner.png",
  altText:"toner image",
  productBrand:"Pixi",
  productName:"Glow Toner",
  purchaseDate:"01/01/2023",
  expiryDate:"01/01/2024",},

 {  id:3,
    imageSrc:"images/Moist.png",
 altText:"Moist image",
 productBrand:"Farmacy",
 productName:"Honey Drop",
 purchaseDate:"01/01/2023",
 expiryDate:"01/01/2024",},

{   id:4, 
    imageSrc:"images/Serum1.png",
altText:"Serum1 image",
productBrand:"The Ordinary",
productName:"Niacinimide Serum",
purchaseDate:"01/01/2023",
expiryDate:"01/01/2024",},

{   id:5, 
    imageSrc:"images/Serum2.png",
altText:"Serum2 image",
productBrand:"Beauty of Joseon",
productName:"Glow Serum",
purchaseDate:"01/01/2023",
expiryDate:"01/01/2024",},

{   id:6, 
    imageSrc:"images/Sunscreen.png",
altText:"Sunscreen image",
productBrand:"Supergoop",
productName:"Unseen sunscreen",
purchaseDate:"01/01/2023",
expiryDate:"01/01/2024",},
];
export default products;
